---
title: "LPS/PHIL 31 Ryan Chen's Discussion Section Notes"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

# Introduction

This is a collection of notes for LPS 31 Fall 2023 Discussion Sections led by Ryan Chen (Discussion Sections: Monday and Wednesday from 5-5:50 pm). All students are welcome to look at and use these notes for studying and practice.

## Content of the Notes

These notes will typically include the material which I cover in discussion. For example, if I go over a practice problem in discussion, then that practice problem will be written up as content in these notes (with solutions). Sometimes material which I planned to cover in discussion, but which I did not have time to cover will also appear in these notes. Students will be notified of when this extra material exists. Finally, these notes will contain extra practice problems and if time permits, solutions to those problems.   

## How to Use these Notes

There are three primary use cases for these notes:

1. If you miss discussion and want to know what we covered in discussion, these notes will cover the core material which I discuss.
1. If you need more practice with problems outside of homework, I will be inserting extra practice problems in these notes.
1. If you need a quick review of core concepts, then these notes should be useful as each note will take *at most* 10-15 minutes to read.
